spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    # Relative path form current dir
    url: jdbc:h2:./db/linkdb
    #     tcp: jdbc:h2:tcp://localhost:9092/./db/linkdb
    username: sa
    password:

  data.rest:
    basePath: /api
    defaultPageSize: 20
    returnBodyOnCreate: true

logging:
  level:
    root: WARN
    com.yourcodereview.melnikov.task2: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true
